### ISSUE TITLE
motor_map_t in tmc2209hal.c and tmc2209hal.h defined nowhere 

### ISSUE THREAD

**Issue by Adar70** [terjeio/Trinamic-library#11]

**Comment by terjeio** [comment]
Sorry for the late reply, somehow notifications were turned off for this repo.

The *hal.h/*hal.c files are for a higher level API used by the [grblHAL project](https://github.com/grblHAL). [motor_map_t](https://github.com/grblHAL/core/blob/ac93c81590c66b5f78412e0584a084557157091f/hal.h#L209-L218) is defined here.
