### ISSUE TITLE
TMC2209 support for ganged axis

### ISSUE THREAD

**Issue by dzervas** [terjeio/Trinamic-library#4]
Currently the library is unaware of ganged X/Y/Z axis so tinkering with them and changing their settings is not possible. I think that due to this the initialization fails too due to the amount of successful writes that happen which are checked [here](https://github.com/terjeio/Trinamic-library/blob/master/tmc2209.c#L165)

grblhal expects axis X2/Y2/Z2 but this lib sets up A, B and C

**Comment by morestart** [comment]
do you know how to use this libiary make StallGuard work?
