### ISSUE TITLE
Found a typo in trinamic.c

### ISSUE THREAD

**Issue by rcKeith** [terjeio/Trinamic-library#8]
Hi
I was struggling to get the XYZA to show up in ioSender as the screenshot shows
I know I could just set it via the interface but I will be offering the firmware as a free download to the CNC foam-cutting community and I'm sure I would get some users who would struggle. So the aim is to make all the defaults in the eeprom.
![image](https://github.com/terjeio/Trinamic-library/assets/42382799/5f2bc6f6-a82c-4fa5-b7c6-505ca89cda44)
 and after a few hours of head scratching and searching the code I found at line 424 in trinamic.c
 **_trinamic.driver_enable.z = TMC_A_ENABLE_**;
changed it to 
**_trinamic.driver_enable.a = TMC_A_ENABLE;_**
![image](https://github.com/terjeio/Trinamic-library/assets/42382799/340af626-a954-485b-818f-dd2bb900a8e1)
 All working fine now, thanks for a great library. This going to power a 4-axis foam cutter using the SKR Pico.  I had great success with the grbl Mega 5X but it is time to move on now.  Should have some videos out soon.
Keith

**Comment by terjeio** [comment]
Sorry for the late reply, somehow notifications were turned off for this repo.

This issue was fixed a while ago so closing this.
